# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64e4f2c14e11d61b70327e8d632153f5aa7bcdcb7c3a1499ee429d767991f454ca65789eb23a97a7bf8b5076c03d103e1dba6b10198b3d2ea1e6e12caa7e4f9a

test:
  secret_key_base: d58b573a837f5fa83f121b4a3b9145b4a98fcc4de6094646608e740d5d9b0db4a74716fd355cfed164e6e1f965f7a7fddac5f6f71760d20aabd1354206995ca7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
